project:
  type: website
  
  output-dir: docs

website:
  title: "Bebop-Paleo"
  navbar:
    title: "Daniel Cusimano"
    background: orange
    foreground: black
    right:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: superhero
    css: styles.css
    toc: true



